import { Client } from 'oicq';

const OICQAPINameList = [
  'pickGroup',
  'pickFriend',
  'pickMember',
  'pickUser',
  'pickDiscuss',
  'login',
  'setOnlineStatus',
  'setNickname',
  'setGender',
  'setBirthday',
  'setDescription',
  'setSignature',
  'setAvatar',
  'getRoamingStamp',
  'deleteStamp',
  'getSystemMsg',
  'addClass',
  'deleteClass',
  'renameClass',
  'reloadFriendList',
  'reloadStrangerList',
  'reloadGroupList',
  'reloadBlackList',
  'cleanCache',
  'getVideoUrl',
  'getForwardMsg',
  'makeForwardMsg',
  'getCookies',
  'getCsrfToken',
  'getFriendList',
  'getGroupList',
  'getStrangerList',
  'getStrangerInfo',
  'getGroupInfo',
  'getGroupMemberList',
  'getGroupMemberInfo',
  'sendPrivateMsg',
  'sendGroupMsg',
  'sendDiscussMsg',
  'sendTempMsg',
  'deleteMsg',
  'reportReaded',
  'getMsg',
  'getChatHistory',
  'setGroupAnonymousBan',
  'setGroupAnonymous',
  'setGroupWholeBan',
  'setGroupName',
  'sendGroupNotice',
  'setGroupAdmin',
  'setGroupSpecialTitle',
  'setGroupCard',
  'setGroupKick',
  'setGroupBan',
  'setGroupLeave',
  'sendGroupPoke',
  'addFriend',
  'deleteFriend',
  'inviteFriend',
  'sendLike',
  'setPortrait',
  'setGroupPortrait',
  'acquireGfs',
  'setFriendAddRequest',
  'setGroupAddRequest',
  'sendOidb',
  'sliderLogin',
  'sendSMSCode',
  'submitSMSCode',
] as const;
export type OICQAPINames = (typeof OICQAPINameList)[number];
export type OICQAPI = Pick<Client, OICQAPINames>;

export default function proxyOicqApi(client: Client): OICQAPI {
  return new Proxy(client, {
    get(target, p: OICQAPINames) {
      return OICQAPINameList.includes(p) ? target[p].bind(target) : undefined;
    },
  });
}
